# Generated by Django 3.2.12 on 2022-03-01 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=255, null=True)),
                ('steps', models.JSONField()),
                ('cook_temp', models.IntegerField()),
                ('cook_time', models.IntegerField()),
                ('yield_name', models.CharField(max_length=255, null=True)),
                ('yield_quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('PUB', 'Public'), ('PRV', 'Private')], default='PRV', max_length=3)),
                ('catagory', models.CharField(choices=[('POP', 'Popular'), ('FAV', 'Favorite')], max_length=3)),
                ('notes', models.TextField(blank=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
