# Generated by Django 3.2.12 on 2022-03-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20220301_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='status',
            new_name='unit',
        ),
        migrations.AddField(
            model_name='step',
            name='measure',
            field=models.CharField(choices=[('GRM', 'Gram'), ('CUP', 'Cup')], default='CUP', max_length=3),
        ),
    ]
