# Generated by Django 3.2.12 on 2022-03-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_catagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='catagory',
            field=models.CharField(choices=[('POP', 'Popular'), ('FAV', 'Favorite'), ('ALL', 'All')], max_length=3, null=True),
        ),
    ]
