# Generated by Django 3.2.12 on 2022-03-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20220301_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='amount_unit',
        ),
        migrations.RemoveField(
            model_name='step',
            name='unit',
        ),
        migrations.AlterField(
            model_name='step',
            name='measure',
            field=models.CharField(choices=[('GRM', 'Grams'), ('CUP', 'Cups'), ('OUC', 'Ounces'), ('LBS', 'Pounds'), ('UNT', 'Unit')], default='UNT', max_length=3),
        ),
    ]
