# Generated by Django 3.2.12 on 2022-03-02 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_step_measure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='measure',
            field=models.CharField(choices=[('GRM', 'Grams'), ('CUP', 'Cups'), ('OUC', 'Ounces'), ('LBS', 'Pounds'), ('UNT', 'Unit-Type')], default='UNT', max_length=3),
        ),
    ]
